Update dotnet.yml

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -24,6 +24,13 @@ jobs:
     - name: Build
       run: dotnet build --no-restore
     - name: Test
-      run: dotnet test -v n
+      run: dotnet test -v n --logger "trx;LogFileName=test-results.trx"
       env:
         Database__ConnectionString: "server=localhost;user=root;password=root;database=plm_ssp_testing"
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: xUnit Tests            # Name of the check run which will be created
+        path: test-results.trx   # Path to test results
+        reporter: dotnet-trx
